/** All supported longhand CSS property names (kebab-case). */
export const LONGHAND_PROPERTIES = new Set([
  'color',
  'background-color',
  'font-weight',
  'font-style',
  'text-decoration',
  'text-decoration-style',
  'text-decoration-color',
  'text-align',
  'vertical-align',
  'text-overflow',
  'white-space',
  'overflow',
  'overflow-wrap',
  'word-break',
  'opacity',
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'border-style',
  'border-color',
  'border-width',
  'box-sizing',
  'display',
  'flex-direction',
  'flex-wrap',
  'flex-grow',
  'flex-shrink',
  'flex-basis',
  'row-gap',
  'column-gap',
  'justify-content',
  'align-items',
  'align-self',
  'position',
  'top',
  'left',
  'z-index',
]);

/** Supported shorthand CSS property names (kebab-case). */
export const SHORTHAND_PROPERTIES = new Set(['padding', 'margin', 'gap', 'flex']);
