import {describe, it} from 'vitest';

describe('MutationObserver integration', () => {
  it.todo(
    'batches attribute, characterData, and childList records generated by real document mutations',
  );
});
