export const INITIAL_VALUES: Record<string, string> = {
  color: '',
  cursor: '',
  'font-weight': 'normal',
  'font-style': 'normal',
  'text-decoration': 'none',
  'text-decoration-style': 'solid',
  'text-decoration-color': '',
  'text-align': 'left',
  'white-space': 'normal',
  'overflow-wrap': 'break-word',
  'word-break': 'normal',
  'tab-size': '8',
  opacity: '1',
};
