import {describe, expect, it} from 'vitest';

import {MutationObserver} from '../MutationObserver';
import {Window} from '../Window';

type ObservedRecord = {
  type: string;
  target: unknown;
  attributeName?: string | null;
  oldValue?: string | null;
  addedNodes?: unknown[];
  removedNodes?: unknown[];
};

describe('MutationObserver integration', () => {
  it('batches attribute, characterData, and childList records generated by real document mutations', async () => {
    const document = new Window().document;
    const recordsSeen: ObservedRecord[][] = [];
    const observer = new MutationObserver((records) => {
      recordsSeen.push(records as ObservedRecord[]);
    });

    const container = document.createElement('div');
    const child = document.createElement('span');
    const text = document.createTextNode('hello');
    child.appendChild(text);
    container.appendChild(child);
    document.body.appendChild(container);

    observer.observe(container, {
      subtree: true,
      childList: true,
      attributes: true,
      attributeOldValue: true,
      characterData: true,
      characterDataOldValue: true,
    });

    child.setAttribute('data-state', 'ready');
    text.data = 'updated';
    const badge = document.createElement('strong');
    child.appendChild(badge);
    child.removeChild(badge);

    await Promise.resolve();

    expect(recordsSeen).toHaveLength(1);
    expect(recordsSeen[0]).toHaveLength(4);
    expect(recordsSeen[0]?.map((record) => record.type)).toEqual([
      'attributes',
      'characterData',
      'childList',
      'childList',
    ]);
    expect(recordsSeen[0]?.[0]).toMatchObject({
      target: child,
      attributeName: 'data-state',
      oldValue: null,
    });
    expect(recordsSeen[0]?.[1]).toMatchObject({
      target: text,
      oldValue: 'hello',
    });
    expect(recordsSeen[0]?.[2]?.addedNodes).toEqual([badge]);
    expect(recordsSeen[0]?.[3]?.removedNodes).toEqual([badge]);
  });
});
